/* Generated By:JavaCC: Do not edit this line. FOMConstants.java */
package org.portico.impl.hla13.fomparser;

public interface FOMConstants
{

	int EOF = 0;
	int SINGLE_LINE_COMMENT = 2;
	int P_OPEN = 8;
	int P_CLOSE = 9;
	int FED = 10;
	int FEDERATION = 11;
	int FEDVERSION = 12;
	int SPACES = 13;
	int SPACE = 14;
	int DIMENSION = 15;
	int OBJECTS = 16;
	int CLASS = 17;
	int ATTRIBUTE = 18;
	int INTERACTIONS = 19;
	int PARAMETER = 20;
	int STRING = 27;
	int CHAR = 28;
	int ALPHA = 29;
	int NUMERIC = 30;
	int SYMBOL = 31;

	int DEFAULT = 0;
	int IN_SINGLE_LINE_COMMENT = 1;

	String[] tokenImage =
	    { "<EOF>", "\";;\"", "<SINGLE_LINE_COMMENT>", "<token of kind 3>", "\" \"", "\"\\t\"",
	     "\"\\r\"", "\"\\n\"", "\"(\"", "\")\"", "<FED>", "<FEDERATION>", "<FEDVERSION>",
	     "<SPACES>", "<SPACE>", "<DIMENSION>", "<OBJECTS>", "<CLASS>", "<ATTRIBUTE>",
	     "<INTERACTIONS>", "<PARAMETER>", "\"v1.3\"", "\"v1_3\"", "\"reliable\"",
	     "\"best_effort\"", "\"timestamp\"", "\"receive\"", "<STRING>", "<CHAR>", "<ALPHA>",
	     "<NUMERIC>", "<SYMBOL>", };

}
