#!/bin/sh
DEVELOPMENT_HOME=$PWD
ANT_HOME=$DEVELOPMENT_HOME/system/ant/apache-ant-1.8.4-patched
ANT_LIB=$ANT_HOME/lib/:$DEVELOPMENT_HOME/system/ant-optional/

export DEVELOPMENT_HOME ANT_HOME ANT_LIB

$ANT_HOME/bin/ant -lib $ANT_LIB $*

