/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_portico_impl_cpp13_FederateAmbassadorLink */

#ifndef _Included_org_portico_impl_cpp13_FederateAmbassadorLink
#define _Included_org_portico_impl_cpp13_FederateAmbassadorLink
#ifdef __cplusplus
extern "C" {
#endif
	
/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    announceSynchronizationPoint
 * Signature: (ILjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_announceSynchronizationPoint
  (JNIEnv *, jobject, jint, jstring, jbyteArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributeIsNotOwned
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributeIsNotOwned
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributeOwnedByRTI
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributeOwnedByRTI
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributeOwnershipAcquisitionNotification
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributeOwnershipAcquisitionNotification
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributeOwnershipDivestitureNotification
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributeOwnershipDivestitureNotification
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributeOwnershipUnavailable
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributeOwnershipUnavailable
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributesInScope
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributesInScope
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    attributesOutOfScope
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_attributesOutOfScope
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    confirmAttributeOwnershipAcquisitionCancellation
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_confirmAttributeOwnershipAcquisitionCancellation
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    discoverObjectInstance
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_discoverObjectInstance
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    federationNotRestored
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_federationNotRestored
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    federationNotSaved
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_federationNotSaved
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    federationRestoreBegun
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_federationRestoreBegun
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    federationRestored
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_federationRestored
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    federationSaved
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_federationSaved
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    federationSynchronized
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_federationSynchronized
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    informAttributeOwnership
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_informAttributeOwnership
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    initiateFederateRestore
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_initiateFederateRestore
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    initiateFederateSave
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_initiateFederateSave
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    provideAttributeValueUpdate
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_provideAttributeValueUpdate
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3B
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[BDI)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3BDI
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jdouble, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3B
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[BDI)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3BDI
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jdouble, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_removeObjectInstance__II_3B
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[BDI)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_removeObjectInstance__II_3BDI
  (JNIEnv *, jobject, jint, jint, jbyteArray, jdouble, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    requestAttributeOwnershipAssumption
 * Signature: (II[I[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_requestAttributeOwnershipAssumption
  (JNIEnv *, jobject, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    requestAttributeOwnershipRelease
 * Signature: (II[I[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_requestAttributeOwnershipRelease
  (JNIEnv *, jobject, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    requestFederationRestoreFailed
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_requestFederationRestoreFailed
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    requestFederationRestoreSucceeded
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_requestFederationRestoreSucceeded
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    requestRetraction
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_requestRetraction
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    startRegistrationForObjectClass
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_startRegistrationForObjectClass
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    stopRegistrationForObjectClass
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_stopRegistrationForObjectClass
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    synchronizationPointRegistrationFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_synchronizationPointRegistrationFailed
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    synchronizationPointRegistrationSucceeded
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_synchronizationPointRegistrationSucceeded
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    timeAdvanceGrant
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_timeAdvanceGrant
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    timeConstrainedEnabled
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_timeConstrainedEnabled
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    timeRegulationEnabled
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_timeRegulationEnabled
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    turnInteractionsOff
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_turnInteractionsOff
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    turnInteractionsOn
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_turnInteractionsOn
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    turnUpdatesOffForObjectInstance
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_turnUpdatesOffForObjectInstance
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp13_FederateAmbassadorLink
 * Method:    turnUpdatesOnForObjectInstance
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp13_FederateAmbassadorLink_turnUpdatesOnForObjectInstance
  (JNIEnv *, jobject, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
