/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_portico_impl_cpp1516e_FederateAmbassadorLink */

#ifndef _Included_org_portico_impl_cpp1516e_FederateAmbassadorLink
#define _Included_org_portico_impl_cpp1516e_FederateAmbassadorLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    connectionLost
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_connectionLost
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    synchronizationPointRegistrationSucceeded
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_synchronizationPointRegistrationSucceeded
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    synchronizationPointRegistrationFailed
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_synchronizationPointRegistrationFailed
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    announceSynchronizationPoint
 * Signature: (ILjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_announceSynchronizationPoint
  (JNIEnv *, jobject, jint, jstring, jbyteArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationSynchronized
 * Signature: (ILjava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationSynchronized
  (JNIEnv *, jobject, jint, jstring, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    initiateFederateSave
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_initiateFederateSave__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    initiateFederateSave
 * Signature: (ILjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_initiateFederateSave__ILjava_lang_String_2D
  (JNIEnv *, jobject, jint, jstring, jdouble);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    initiateFederateSave
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_initiateFederateSave__ILjava_lang_String_2J
  (JNIEnv *, jobject, jint, jstring, jlong);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationSaved
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationSaved
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationNotSaved
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationNotSaved
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationSaveStatusResponse
 * Signature: (I[I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationSaveStatusResponse
  (JNIEnv *, jobject, jint, jintArray, jobjectArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    requestFederationRestoreSucceeded
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_requestFederationRestoreSucceeded
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    requestFederationRestoreFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_requestFederationRestoreFailed
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationRestoreBegun
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationRestoreBegun
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    initiateFederateRestore
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_initiateFederateRestore
  (JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationRestored
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationRestored
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationNotRestored
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationNotRestored
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    federationRestoreStatusResponse
 * Signature: (I[I[I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_federationRestoreStatusResponse
  (JNIEnv *, jobject, jint, jintArray, jintArray, jobjectArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reportFederationExecutions
 * Signature: (I[Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reportFederationExecutions
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    startRegistrationForObjectClass
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_startRegistrationForObjectClass
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    stopRegistrationForObjectClass
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_stopRegistrationForObjectClass
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    turnInteractionsOn
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_turnInteractionsOn
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    turnInteractionsOff
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_turnInteractionsOff
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    objectInstanceNameReservationSucceeded
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_objectInstanceNameReservationSucceeded
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    multipleObjectInstanceNameReservationSucceeded
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_multipleObjectInstanceNameReservationSucceeded
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    objectInstanceNameReservationFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_objectInstanceNameReservationFailed
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    multipleObjectInstanceNameReservationFailed
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_multipleObjectInstanceNameReservationFailed
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    discoverObjectInstance
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_discoverObjectInstance__IIILjava_lang_String_2
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    discoverObjectInstance
 * Signature: (IIILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_discoverObjectInstance__IIILjava_lang_String_2I
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[BIII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3BIII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[BIIDII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3BIIDII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jdouble, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[BIIJII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3BIIJII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jlong, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[BIIDIII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3BIIDIII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jdouble, jint, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reflectAttributeValues
 * Signature: (II[I[[B[BIIJIII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reflectAttributeValues__II_3I_3_3B_3BIIJIII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jlong, jint, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[BIII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3BIII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[BIIDII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3BIIDII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jdouble, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[BIIJII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3BIIJII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jlong, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[BIIDIII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3BIIDIII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jdouble, jint, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    receiveInteraction
 * Signature: (II[I[[B[BIIJIII[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_receiveInteraction__II_3I_3_3B_3BIIJIII_3I
  (JNIEnv *, jobject, jint, jint, jintArray, jobjectArray, jbyteArray, jint, jint, jlong, jint, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[BII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_removeObjectInstance__II_3BII
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[BIDII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_removeObjectInstance__II_3BIDII
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jdouble, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[BIJII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_removeObjectInstance__II_3BIJII
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jlong, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[BIDIII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_removeObjectInstance__II_3BIDIII
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jdouble, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    removeObjectInstance
 * Signature: (II[BIJIII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_removeObjectInstance__II_3BIJIII
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jlong, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    attributesInScope
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_attributesInScope
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    attributesOutOfScope
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_attributesOutOfScope
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    provideAttributeValueUpdate
 * Signature: (II[I[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_provideAttributeValueUpdate
  (JNIEnv *, jobject, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    turnUpdatesOnForObjectInstance
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_turnUpdatesOnForObjectInstance__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    turnUpdatesOnForObjectInstance
 * Signature: (II[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_turnUpdatesOnForObjectInstance__II_3ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jint, jintArray, jstring);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    turnUpdatesOffForObjectInstance
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_turnUpdatesOffForObjectInstance
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    confirmAttributeTransportationTypeChange
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_confirmAttributeTransportationTypeChange
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    confirmInteractionTransportationTypeChange
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_confirmInteractionTransportationTypeChange
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reportAttributeTransportationType
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reportAttributeTransportationType
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    reportInteractionTransportationType
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_reportInteractionTransportationType
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    requestAttributeOwnershipAssumption
 * Signature: (II[I[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_requestAttributeOwnershipAssumption
  (JNIEnv *, jobject, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    requestDivestitureConfirmation
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_requestDivestitureConfirmation
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    attributeOwnershipAcquisitionNotification
 * Signature: (II[I[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_attributeOwnershipAcquisitionNotification
  (JNIEnv *, jobject, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    attributeOwnershipUnavailable
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_attributeOwnershipUnavailable
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    requestAttributeOwnershipRelease
 * Signature: (II[I[B)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_requestAttributeOwnershipRelease
  (JNIEnv *, jobject, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    confirmAttributeOwnershipAcquisitionCancellation
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_confirmAttributeOwnershipAcquisitionCancellation
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    informAttributeOwnership
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_informAttributeOwnership
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    attributeIsNotOwned
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_attributeIsNotOwned
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    attributeIsOwnedByRTI
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_attributeIsOwnedByRTI
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    timeRegulationEnabled
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_timeRegulationEnabled__ID
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    timeRegulationEnabled
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_timeRegulationEnabled__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    timeConstrainedEnabled
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_timeConstrainedEnabled__ID
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    timeConstrainedEnabled
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_timeConstrainedEnabled__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    timeAdvanceGrant
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_timeAdvanceGrant__ID
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    timeAdvanceGrant
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_timeAdvanceGrant__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_portico_impl_cpp1516e_FederateAmbassadorLink
 * Method:    requestRetraction
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_FederateAmbassadorLink_requestRetraction
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
