/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_portico_impl_cpp1516e_ExceptionManager */

#ifndef _Included_org_portico_impl_cpp1516e_ExceptionManager
#define _Included_org_portico_impl_cpp1516e_ExceptionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_portico_impl_cpp1516e_ExceptionManager
 * Method:    pushException
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_portico_impl_cpp1516e_ExceptionManager_pushException
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
